name: mcp-servers
region: nyc1

services:
  # Management Interface with SSH
  - name: mcp-manager
    source_dir: /
    github:
      repo: klogins-hash/mcp-servers-deployment
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-s  # Slightly larger for management
    health_check:
      http_path: /health
    envs:
      - key: GITHUB_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: DIGITALOCEAN_TOKEN  
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_REPO
        value: klogins-hash/mcp-servers-deployment
      - key: SSH_ENABLED
        value: "true"
    run_command: |
      bash -c "
      /app/scripts/install-manager.sh && 
      /app/scripts/setup-ssh.sh && 
      python /app/scripts/health-check.py
      "

  # Default MCP Servers (can be managed via SSH)
  - name: mcp-fetch
    source_dir: /
    github:
      repo: klogins-hash/mcp-servers-deployment
      branch: main
      deploy_on_push: true
    run_command: uvx mcp-server-fetch --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    envs:
      - key: MCP_SERVER_TYPE
        value: fetch
      - key: ROBOTS_TXT_RESPECT
        value: "true"
